workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        TAG_NAME: apps1
      when: always
  
stages:
- deploy
deploy:
  stage: deploy
  tags:
    - ${TAG_NAME}
  script:
    - docker compose down
   # #- docker rmi ecomlab_frontend-lkt-app
    - docker compose up -d
    